### ISSUE TITLE
Create snapshot from dumps

### ISSUE THREAD

**Issue by keltroth** [jonaslu/sider#32]
Add a way to create a snapshot from a dump file/directory.

Examples : 
```shell
sider snapshot add mariadb mymariadb ./mydump.sql
```

```shell
sider snapshot add mongodb mymongodb ./mongodump/
```

**Comment by keltroth** [comment]
I was speaking about the sql limitation, I hadn't find this explanation though... 

For the mongo case, can you load from a `mongodump` generated file ? My understanding is that I need to grab the 'data' folder, not export data...

**Comment by jonaslu** [comment]
Yes, it's the data-folder. The path pointed to by the conf-parameter dbPath: https://www.mongodb.com/docs/manual/tutorial/manage-mongodb-processes/#specify-a-data-directory

Ingesting the output of mongodump comes with the same problems as reading an `.sql` file, so the workaround would be the same. Run mongorestore against the empty snapshot created by sider:
```
sider db empty mongodb mymongodb
...wait some...
mongorestore -h 127.0.0.1 dump-dir/
```

I'll clarify in the README, thanks for noticing!

**Comment by keltroth** [comment]
So to summarize, to make it work from a dump file (sql or mongodump), I need to create an empty snapshot and load data in a new database ?

**Comment by jonaslu** [comment]
Correct

**Comment by keltroth** [comment]
Thanks, it's very clear now. I had the wrong point of view from the beginning !
